/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UML;

import Dao.ChungTuCTDAO;
import Dao.ChungTuDAO;
import Dao.SPKhoDAO;
import Help.Auth;
import static Help.ValidateHelper.*;
import java.awt.Color;
import static Help.ColorHelper.*;
import Help.DialogHelper;
import java.awt.Font;
import static Help.ImageHelper.*;
import Model.ChungTu;
import Model.ChungTuCT;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class DuyetHang_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form DuyetHang_JFrame
     */
    int index = -1;
    List<ChungTu> listDuyet;
    List<ChungTu> listDuyetNhap;
    List<ChungTu> listDuyetXuat;
    List<ChungTuCT> listChungTuCT;
    ChungTuDAO daoChungTu = new ChungTuDAO();
    ChungTuCTDAO daoChungTuCT = new ChungTuCTDAO();
    SPKhoDAO daoSPKho = new SPKhoDAO();

    public DuyetHang_JFrame() {
        initComponents();
        init();
        loadDuyet();
        lblDuyet.setText(String.valueOf(daoChungTu.countChuaDuyet()));
        lblNhap.setText(String.valueOf(daoChungTu.countChuaDuyetNhap()));
        lblXuat.setText(String.valueOf(daoChungTu.countChuaDuyetXuat()));
        Thread thread = new Thread() {
            @Override
            public void run() {
                while (true) {
                    int duyet = Integer.parseInt(lblDuyet.getText().trim());
                    int duyetNhap = Integer.parseInt(lblNhap.getText().trim());
                    int duyetXuat = Integer.parseInt(lblXuat.getText().trim());
                    int countDuyet = daoChungTu.countChuaDuyet();
                    int countDuyetNhap = daoChungTu.countChuaDuyetNhap();
                    int countDuyetXuat = daoChungTu.countChuaDuyetXuat();
                    int count = 0;
                    if (duyet < countDuyet || duyet > countDuyet) {
                        lblDuyet.setText(String.valueOf(countDuyet));
                        count++;
                    }

                    if (duyetNhap < countDuyetNhap || duyetNhap > countDuyetNhap) {
                        lblNhap.setText(String.valueOf(countDuyetNhap));
                        count++;
                    }

                    if (duyetXuat < countDuyetXuat || duyetXuat > countDuyetXuat) {
                        lblXuat.setText(String.valueOf(countDuyetXuat));
                        count++;
                    }

                    if (count != 0) {
                        changeComboBox();
                    }

                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DuyetHang_JFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        thread.start();
    }

    void init() {
        designTable(false, new Color(0, 102, 255), Color.white, Plain, tblDuyet);
        designTable(false, new Color(0, 102, 255), Color.white, Plain, tblChiTiet);
        designComboBox(new Color(51, 102, 255), Color.white, Plain, cboLoaiChungTu);
        jPanel1.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDuyetHang = new javax.swing.JPanel();
        lblDuyetHang = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        pnlLoaiChungTu = new javax.swing.JPanel();
        lblLoaiChungTu = new javax.swing.JLabel();
        lblDuyetChungTu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        lblXemChiTiet = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDuyet = new javax.swing.JTable();
        lblTaoPhieu = new javax.swing.JLabel();
        cboLoaiChungTu = new javax.swing.JComboBox<>();
        lblThongBao = new javax.swing.JLabel();
        lblTaoPhieu1 = new javax.swing.JLabel();
        jPanel1 = new RoundedPanel(20,new Color(255,102,102));
        lblChuaDuyet = new javax.swing.JLabel();
        lblDuyet = new javax.swing.JLabel();
        pnlDonDaDuyet1 = new keeptoo.KGradientPanel();
        jLabel3 = new javax.swing.JLabel();
        lblXuat = new javax.swing.JLabel();
        pnlDonDaDuyet = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();
        lblNhap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duyệt hàng");
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDuyetHang.setBackground(new java.awt.Color(51, 51, 255));
        pnlDuyetHang.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(0, 0, 0)));
        pnlDuyetHang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlDuyetHangMouseDragged(evt);
            }
        });
        pnlDuyetHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlDuyetHangMousePressed(evt);
            }
        });
        pnlDuyetHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDuyetHang.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblDuyetHang.setForeground(new java.awt.Color(255, 255, 255));
        lblDuyetHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logo.png"))); // NOI18N
        lblDuyetHang.setText("Duyệt hàng");
        pnlDuyetHang.add(lblDuyetHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblBack.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Backs.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBackMouseExited(evt);
            }
        });
        pnlDuyetHang.add(lblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, 70, 50));

        getContentPane().add(pnlDuyetHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 70));

        pnlLoaiChungTu.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoaiChungTu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlLoaiChungTu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoaiChungTu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLoaiChungTu.setForeground(new java.awt.Color(0, 102, 204));
        lblLoaiChungTu.setText("Loại chứng từ");
        pnlLoaiChungTu.add(lblLoaiChungTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 12, -1, -1));

        lblDuyetChungTu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDuyetChungTu.setForeground(new java.awt.Color(0, 102, 204));
        lblDuyetChungTu.setText("Duyệt chứng từ");
        pnlLoaiChungTu.add(lblDuyetChungTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 47, -1, -1));

        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Ct", "Mã Sp", "Tên Sp", "Loại Sản Phẩm", "Giá Sp", "Số Lượng", "Đơn Vị Tính", "Tên Nhà Cc", "Mã lô hàng", "Ngày Nhập", "Hình"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTiet.setRowHeight(25);
        tblChiTiet.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblChiTiet);

        pnlLoaiChungTu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 339, 1216, 214));

        lblXemChiTiet.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblXemChiTiet.setForeground(new java.awt.Color(0, 102, 204));
        lblXemChiTiet.setText("Xem chi tiết");
        pnlLoaiChungTu.add(lblXemChiTiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 299, -1, 34));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tblDuyet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Chứng Từ", "Người tạo", "Loại Chứng Từ", "Ngày Tạo", "Trạng thái", "Mã Khách Hàng", "Tổng tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDuyet.setGridColor(new java.awt.Color(204, 204, 204));
        tblDuyet.setRowHeight(25);
        tblDuyet.setShowVerticalLines(false);
        tblDuyet.getTableHeader().setReorderingAllowed(false);
        tblDuyet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDuyetMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDuyet);

        pnlLoaiChungTu.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 88, 812, 198));

        lblTaoPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblTaoPhieu.setFont(new java.awt.Font("UVN Chim Bien", 1, 24)); // NOI18N
        lblTaoPhieu.setForeground(new java.awt.Color(0, 51, 255));
        lblTaoPhieu.setText("Duyệt hàng");
        lblTaoPhieu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        lblTaoPhieu.setOpaque(true);
        lblTaoPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaoPhieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTaoPhieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTaoPhieuMouseExited(evt);
            }
        });
        pnlLoaiChungTu.add(lblTaoPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(702, 297, -1, -1));

        cboLoaiChungTu.setBackground(new java.awt.Color(51, 102, 255));
        cboLoaiChungTu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Nhập hàng", "Xuất hàng" }));
        cboLoaiChungTu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiChungTuItemStateChanged(evt);
            }
        });
        pnlLoaiChungTu.add(cboLoaiChungTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 53, 446, 29));

        lblThongBao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(51, 102, 255));
        lblThongBao.setText("Thông báo");
        pnlLoaiChungTu.add(lblThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(959, 12, -1, -1));

        lblTaoPhieu1.setBackground(new java.awt.Color(255, 255, 255));
        lblTaoPhieu1.setFont(new java.awt.Font("UVN Chim Bien", 1, 24)); // NOI18N
        lblTaoPhieu1.setForeground(new java.awt.Color(0, 51, 255));
        lblTaoPhieu1.setText("Hủy hàng");
        lblTaoPhieu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        lblTaoPhieu1.setOpaque(true);
        lblTaoPhieu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaoPhieu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTaoPhieu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTaoPhieu1MouseExited(evt);
            }
        });
        pnlLoaiChungTu.add(lblTaoPhieu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 297, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChuaDuyet.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblChuaDuyet.setForeground(new java.awt.Color(255, 255, 255));
        lblChuaDuyet.setText("Chưa duyệt:");
        jPanel1.add(lblChuaDuyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 30));

        lblDuyet.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblDuyet.setForeground(new java.awt.Color(153, 255, 204));
        lblDuyet.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDuyet.setText("5");
        jPanel1.add(lblDuyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 20, 90, -1));

        pnlDonDaDuyet1.setkEndColor(new java.awt.Color(255, 153, 255));
        pnlDonDaDuyet1.setkStartColor(new java.awt.Color(204, 204, 0));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Chuyển hàng:");

        lblXuat.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblXuat.setForeground(new java.awt.Color(153, 255, 204));
        lblXuat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblXuat.setText("5");

        javax.swing.GroupLayout pnlDonDaDuyet1Layout = new javax.swing.GroupLayout(pnlDonDaDuyet1);
        pnlDonDaDuyet1.setLayout(pnlDonDaDuyet1Layout);
        pnlDonDaDuyet1Layout.setHorizontalGroup(
            pnlDonDaDuyet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonDaDuyet1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(85, 85, 85))
        );
        pnlDonDaDuyet1Layout.setVerticalGroup(
            pnlDonDaDuyet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonDaDuyet1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlDonDaDuyet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(pnlDonDaDuyet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 350, -1));

        pnlDonDaDuyet.setkEndColor(new java.awt.Color(204, 255, 153));
        pnlDonDaDuyet.setkStartColor(new java.awt.Color(204, 51, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nhập hàng:");

        lblNhap.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        lblNhap.setForeground(new java.awt.Color(153, 255, 204));
        lblNhap.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblNhap.setText("5");

        javax.swing.GroupLayout pnlDonDaDuyetLayout = new javax.swing.GroupLayout(pnlDonDaDuyet);
        pnlDonDaDuyet.setLayout(pnlDonDaDuyetLayout);
        pnlDonDaDuyetLayout.setHorizontalGroup(
            pnlDonDaDuyetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonDaDuyetLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(lblNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        pnlDonDaDuyetLayout.setVerticalGroup(
            pnlDonDaDuyetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDonDaDuyetLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlDonDaDuyetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel1.add(pnlDonDaDuyet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 350, -1));

        pnlLoaiChungTu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, 380, 240));

        getContentPane().add(pnlLoaiChungTu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1250, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblTaoPhieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoPhieuMouseEntered
        lblTaoPhieu.setBackground(new Color(0, 51, 255));
        lblTaoPhieu.setForeground(Color.white);
    }//GEN-LAST:event_lblTaoPhieuMouseEntered

    private void lblTaoPhieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoPhieuMouseExited
        lblTaoPhieu.setBackground(Color.white);
        lblTaoPhieu.setForeground(new Color(0, 51, 255));
    }//GEN-LAST:event_lblTaoPhieuMouseExited

    private void pnlDuyetHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDuyetHangMousePressed
        moveFrom(evt);
    }//GEN-LAST:event_pnlDuyetHangMousePressed

    private void pnlDuyetHangMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDuyetHangMouseDragged
        MouseDragged(evt, this);
    }//GEN-LAST:event_pnlDuyetHangMouseDragged

    private void lblTaoPhieu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoPhieu1MouseEntered
        lblTaoPhieu1.setBackground(new Color(0, 51, 255));
        lblTaoPhieu1.setForeground(Color.white);
    }//GEN-LAST:event_lblTaoPhieu1MouseEntered

    private void lblTaoPhieu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoPhieu1MouseExited
        lblTaoPhieu1.setBackground(Color.white);
        lblTaoPhieu1.setForeground(new Color(0, 51, 255));
    }//GEN-LAST:event_lblTaoPhieu1MouseExited

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        dispose();
    }//GEN-LAST:event_lblBackMouseClicked

    private void lblBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseEntered
        lblBack.setIcon(Back2);
    }//GEN-LAST:event_lblBackMouseEntered

    private void lblBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseExited
        lblBack.setIcon(Back1);
    }//GEN-LAST:event_lblBackMouseExited

    private void cboLoaiChungTuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiChungTuItemStateChanged
        // TODO add your handling code here:
        changeComboBox();

    }//GEN-LAST:event_cboLoaiChungTuItemStateChanged

    private void tblDuyetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDuyetMouseClicked
        // TODO add your handling code here:
        index = tblDuyet.getSelectedRow();
        loadChungTuCT();
    }//GEN-LAST:event_tblDuyetMouseClicked

    private void lblTaoPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoPhieuMouseClicked
        // TODO add your handling code here:
        index = tblDuyet.getSelectedRow();
        if (index != -1) {
            update();
            DefaultTableModel model = (DefaultTableModel) tblChiTiet.getModel();
            model.setRowCount(0);
        } else {
            DialogHelper.alert(null, "Vui lòng chọn đơn");
        }
    }//GEN-LAST:event_lblTaoPhieuMouseClicked

    private void lblTaoPhieu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoPhieu1MouseClicked
        // TODO add your handling code here:
        index = tblDuyet.getSelectedRow();
        if (index != -1) {
            delete();
        } else {
            DialogHelper.alert(null, "Vui lòng chọn đơn");
        }
    }//GEN-LAST:event_lblTaoPhieu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DuyetHang_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DuyetHang_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLoaiChungTu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblChuaDuyet;
    private javax.swing.JLabel lblDuyet;
    private javax.swing.JLabel lblDuyetChungTu;
    private javax.swing.JLabel lblDuyetHang;
    private javax.swing.JLabel lblLoaiChungTu;
    private javax.swing.JLabel lblNhap;
    private javax.swing.JLabel lblTaoPhieu;
    private javax.swing.JLabel lblTaoPhieu1;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JLabel lblXemChiTiet;
    private javax.swing.JLabel lblXuat;
    private keeptoo.KGradientPanel pnlDonDaDuyet;
    private keeptoo.KGradientPanel pnlDonDaDuyet1;
    private javax.swing.JPanel pnlDuyetHang;
    private javax.swing.JPanel pnlLoaiChungTu;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JTable tblDuyet;
    // End of variables declaration//GEN-END:variables
    void loadDuyet() {
        DefaultTableModel model = (DefaultTableModel) tblDuyet.getModel();
        model.setRowCount(0);
        listDuyet = daoChungTu.selectDuyet();
        for (ChungTu ct : listDuyet) {
            Object[] ob = {ct.getMaChungTu(), ct.getTenDangNhap(), ct.getLoaiChungTu(), ct.getNgayTao(), ct.getTrangThai(), "Không", ct.getTongTien()};
            model.addRow(ob);
        }
    }

    void loadDuyetNhap() {
        DefaultTableModel model = (DefaultTableModel) tblDuyet.getModel();
        model.setRowCount(0);
        listDuyetNhap = daoChungTu.selectDuyetNhap();
        for (ChungTu ct : listDuyetNhap) {
            Object[] ob = {ct.getMaChungTu(), ct.getTenDangNhap(), ct.getLoaiChungTu(), ct.getNgayTao(), ct.getTrangThai(), "Không", ct.getTongTien()};
            model.addRow(ob);
        }
    }

    void loadDuyetXuat() {
        DefaultTableModel model = (DefaultTableModel) tblDuyet.getModel();
        model.setRowCount(0);
        listDuyetXuat = daoChungTu.selectDuyetXuat();
        for (ChungTu ct : listDuyetXuat) {
            Object[] ob = {ct.getMaChungTu(), ct.getTenDangNhap(), ct.getLoaiChungTu(), ct.getNgayTao(), ct.getTrangThai(), "Không", ct.getTongTien()};
            model.addRow(ob);
        }
    }

    void loadChungTuCT() {
        DefaultTableModel model = (DefaultTableModel) tblChiTiet.getModel();
        model.setRowCount(0);
        String mct = String.valueOf(tblDuyet.getValueAt(index, 0));
        listChungTuCT = daoChungTuCT.selectByConditions(mct);
        for (ChungTuCT ct : listChungTuCT) {
            Object[] ob = {ct.getMaChungTu(), ct.getMaSP(),
                ct.getTenSP(), ct.getLoaiSP(),
                ct.getGia(), ct.getSoLuong(),
                ct.getDonViTinh(), ct.getTenNCC(),
                ct.getMaLoHang(), ct.getNgayNhap(),
                ct.getHinh()};
            model.addRow(ob);
        }
    }

    void changeComboBox() {
        if (cboLoaiChungTu.getSelectedIndex() == 0) {
            loadDuyet();
        } else if (cboLoaiChungTu.getSelectedIndex() == 1) {
            loadDuyetNhap();
        } else {
            loadDuyetXuat();
        }
    }

    void update() {
        String mct = String.valueOf(tblDuyet.getValueAt(index, 0));
        String loaiCT = String.valueOf(tblDuyet.getValueAt(index, 2));
        double tien = Double.parseDouble(String.valueOf(tblDuyet.getValueAt(index, 6)));
        if (loaiCT.equals("Nhập hàng")) {
            new ThanhToan_JFrame(mct, loaiCT, tien).setVisible(true);
        } else {
            if (DialogHelper.confirm(null, "Bạn có muốn duyệt đơn \n" + mct + " không?")) {
                if (daoChungTu.update("Đã duyệt", Auth.user.getTenDn(), mct) == 1) {
                    DefaultTableModel model = (DefaultTableModel) tblChiTiet.getModel();
                    for (int i = 0; i < model.getRowCount(); i++) {
                        String maSP = String.valueOf(tblChiTiet.getValueAt(i, 1));
                        int sl = Integer.parseInt(String.valueOf(tblChiTiet.getValueAt(i, 5)));
                        int check = daoSPKho.truSoLuong(maSP, sl);
                        if (check == 0) {
                            DialogHelper.alert(null, "Không đủ hàng trong kho");
                        }
                    }
                    DialogHelper.alert(null, "Duyệt đơn thành công");
                    model.setRowCount(0);
                } else {
                    DialogHelper.alert(null, "Duyệt đơn thất bại");
                }
            }
        }

    }

    void delete() {
        String mct = String.valueOf(tblDuyet.getValueAt(index, 0));
        if (DialogHelper.confirm(null, "Bạn có muốn xóa đơn có mã \n" + mct + " không ?")) {
            if (daoChungTu.delete(mct) == 1) {
                DefaultTableModel model = (DefaultTableModel) tblChiTiet.getModel();
                model.setRowCount(0);
                DialogHelper.alert(null, "Xóa đơn thành công");
            } else {
                DialogHelper.alert(null, "Xóa đơn thất bại");
            }
        }
    }

    class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;

        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
